apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "kubefox.fullname" . }}-catchall
  labels:
    app.kubernetes.io/component: http-ingress-adapter
    {{- include "kubefox.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/`)
      priority: 1
      kind: Rule
      services:
        - name: kfp-broker
          port: 8080