apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
{{ include "kubefox.operatorMetadata" . }}
rules: # TODO refine access
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
