apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
{{ include "kubefox.operatorMetadata" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubefox.operatorName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubefox.operatorName" . }}
