apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubefox.operatorName" . }}-auth-delegator
  labels:
    {{- include "kubefox.labels" . | nindent 4 }}
  {{- with  .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubefox.operatorName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator