apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
{{ include "kubefox.operatorMetadata" . }}
rules:
  - apiGroups:
      - kubefox.xigxog.io
    resources:
      - "*"
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  
  - apiGroups:
      - kubefox.xigxog.io
    resources:
      - releasemanifests
    verbs:
      - delete

  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - delete
  
  - apiGroups:
      - ""
    resources:
      - namespaces
      - serviceaccounts
      - services
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - statefulsets
      - deployments
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - delete
  
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    resourceNames:
      - {{ include "kubefox.fullname" . }}-operator
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch