apiVersion: apps/v1
kind: Deployment
{{ include "kubefox.operatorMetadata" . }}
spec:
  selector:
    matchLabels:
      {{- include "kubefox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubefox.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      serviceAccountName: {{ include "kubefox.operatorName" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.extraInitContainers }}
      initContainers:
        {{- tpl (toYaml . | nindent 8) $ }}
      {{- end }}
      containers:
        - name: operator
          image: {{ printf "%s:%s" .Values.image.name (.Values.image.tag | default .Chart.AppVersion) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -instance={{ include "kubefox.fullname" . }}
            - -namespace={{ .Release.Namespace }}
            - -vault-url={{ .Values.vault.externalURL | default (printf "https://%s:%s" .Values.vault.fullnameOverride (.Values.vault.server.service.port | toString)) }}
            - -health-addr=0.0.0.0:1111
            - -log-format={{ .Values.log.format | default "json" }}
            - -log-level={{ .Values.log.level | default "info" }}
          ports:
            - name: health
              containerPort: 1111
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.extraContainers }}
          {{- tpl (toYaml . | nindent 8) $ }}
        {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- tpl (toYaml . | nindent 8) $ }}
      {{- end }}
      {{- with .Values.imagePullSecrets -}}
      imagePullSecrets:
      {{- range . -}}
      {{- if typeIs "string" . }}
        - name: {{ . }}
      {{- else if index . "name" }}
        - name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml . | nindent 8) $ }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- tpl (toYaml . | nindent 8) $ }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- tpl (toYaml . | nindent 8) $ }}
      {{- end }}
