apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
{{ include "kubefox.operatorMetadata" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubefox.operatorName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubefox.operatorName" . }}
