# Creates an empty Secret if it does not already exist so that Pods can mount
# it. During Vault initialization the ca.crt will be updated.
{{- $name := printf "%s-root-ca" (include "kubefox.fullname" .) }}
{{- $cur := lookup "v1" "Secret" .Release.Namespace $name }}
{{- if $cur }}
{{ $cur | toYaml }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "kubefox.labels" . | nindent 4 }}
  annotations:
    # Included to prevent warnings when using `kubectl apply`.
    kubectl.kubernetes.io/last-applied-configuration: ""
data:
  ca.crt: ""
{{- end }}