apiVersion: v1
kind: Service
{{ include "kubefox.operatorMetadata" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "kubefox.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
