---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.broker.service.name }}
  labels:
    {{- include "kubefox.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: 127.0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nats.nats.service.name }}
  labels:
    {{- include "kubefox.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: {{ .Values.nats.nats.client.portName }}
      port: {{ .Values.nats.nats.client.port }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vault.server.service.name }}
  labels:
    {{- include "kubefox.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: server
  ports:
    - name: https
      port: {{ .Values.vault.server.service.port }}
      targetPort: {{ .Values.vault.server.service.port }}
