# Generates self signed TLS certificates if they do not already exist.
{{- define "kubefox.tls-secret" -}}
{{- $ns := .root.Release.Namespace }}
{{- $cur := lookup "v1" "Secret" $ns .secName }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .secName }}
  labels:
    {{- include "kubefox.labels" .root | nindent 4 }}
data:
{{- if $cur }}
  {{- toYaml $cur.data | nindent 2 }}
{{- else }}
  {{- $cn := printf "system:node:%s.%s.svc.cluster.local" .svcName $ns }}
  {{- $ip := list "127.0.0.1" }}
  {{- $dns := list "localhost" (.svcName) (printf "%s.%s" .svcName $ns) (printf "%s.%s.svc.cluster.local" .svcName $ns) }}
  {{- $cert := genSignedCert $cn $ip $dns 3650 .ca }}
  ca.crt: {{ .ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
{{- end }}

{{- $ca := genCA "KubeFox CA" 3650 }}

{{- $secName := .Values.telemetry.tls.secret.name }}
{{- $svcName := "kfp-telemetry-agent" }}
{{- $data := dict "secName" $secName "svcName" $svcName "ca" $ca "root" . }}
{{- include "kubefox.tls-secret" $data }}

{{- $secName := .Values.nats.nats.tls.secret.name }}
{{- $svcName := .Values.nats.nats.service.name }}
{{- $data := dict "secName" $secName "svcName" $svcName "ca" $ca "root" . }}
{{- include "kubefox.tls-secret" $data }}


{{- $secName := .Values.runtime.server.tls.secret.name }}
{{- $svcName := .Values.runtime.server.service.name }}
{{- $data := dict "secName" $secName "svcName" $svcName "ca" $ca "root" . }}
{{- include "kubefox.tls-secret" $data }}

{{- $secName := .Values.vault.server.tls.secret.name }}
{{- $svcName := .Values.vault.server.service.name }}
{{- $data := dict "secName" $secName "svcName" $svcName "ca" $ca "root" . }}
{{- include "kubefox.tls-secret" $data }}