apiVersion: v2
type: application
name: kubefox
version: 1.0.3
appVersion: v0.2.5-alpha
description: A Helm chart for the KubeFox Operator.
maintainers:
  - name: John Long (xadhatter)
    email: support@xigxog.io
  - name: Bill Schmidt (BoLB23)
    email: support@xigxog.io
sources:
  - https://github.com/xigxog/kubefox
