apiVersion: v2
type: application
name: kubefox
version: 1.5.1
appVersion: v0.7.2
description: A Helm chart for the KubeFox Operator.
maintainers:
  - name: John Long (xadhatter)
    email: support@xigxog.io
  - name: Bill Schmidt (BoLB23)
    email: support@xigxog.io
sources:
  - https://github.com/xigxog/kubefox
  - https://github.com/xigxog/helm-charts

dependencies:
  - name: vault
    version: 0.28.0
    repository: https://helm.releases.hashicorp.com
    condition: vault.enabled
  - name: opentelemetry-collector
    alias: opentelemetry
    version: 0.91.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: telemetry.enabled
  - name: jaeger
    version: 3.0.7
    repository: https://jaegertracing.github.io/helm-charts
    condition: telemetry.enabled
