apiVersion: v2
type: application
name: kubefox
version: 0.2.0
appVersion: main
description: A Helm chart for the KubeFox Operator.
maintainers:
  - name: John Long (xadhatter)
    email: support@xigxog.io
  - name: Bill Schmidt (BoLB23)
    email: support@xigxog.io
sources:
  - https://github.com/xigxog/kubefox
