nameOverride: ""
fullnameOverride: ""

log:
  format: json # one of ["json", "console"]
  level: info #one of ["debug", "info", "warn", "error"]

image:
  name: ghcr.io/xigxog/kubefox/operator
  tag: main
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: health
  initialDelaySeconds: 5
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /readyz
    port: health
  initialDelaySeconds: 5
  periodSeconds: 15

priorityClassName: ""
imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}

extraLabels: {}
extraAnnotations: {}
extraInitContainers: []
extraContainers: []
extraVolumes: []
