nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/xigxog/kubefox
  tag: main
  pullPolicy: IfNotPresent

broker:
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 32Mi

  # TODO
  # livenessProbe:
  #   failureThreshold: 2
  #   initialDelaySeconds: 5
  #   periodSeconds: 2
  #   successThreshold: 1
  #   timeoutSeconds: 5

  # TODO
  # readinessProbe:
  #   failureThreshold: 2
  #   initialDelaySeconds: 5
  #   periodSeconds: 2
  #   successThreshold: 1
  #   timeoutSeconds: 5

operator:
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 32Mi

priorityClassName: ""
imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}

extraLabels: {}
extraAnnotations: {}
extraInitContainers: []
extraContainers: []
extraVolumes: []
