---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kfp-api-server
  labels:
    app.kubernetes.io/component: api-server
    {{- include "kubefox.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubefox.fullname" . }}-api-server
  labels:
    app.kubernetes.io/component: api-server
    {{- include "kubefox.labels" . | nindent 4 }}
rules:
  - apiGroups: ["k8s.kubefox.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubefox.fullname" . }}-api-server
  labels:
    app.kubernetes.io/component: api-server
    {{- include "kubefox.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubefox.fullname" . }}-api-server
  labels:
    app.kubernetes.io/component: api-server
    {{- include "kubefox.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kfp-api-server
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubefox.fullname" . }}-api-server

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubefox.fullname" . }}-api-server
  labels:
    app.kubernetes.io/component: api-server
    {{- include "kubefox.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kfp-api-server
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubefox.fullname" . }}-api-server
