---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: {{ include "kubefox.fullname" . }}-operator
  labels:
    app.kubernetes.io/component: operator
    {{- include "kubefox.labels" . | nindent 4 }}
spec:
  resources:
    - apiVersion: k8s.kubefox.io/v1alpha1
      resource: componentsets
    - apiVersion: k8s.kubefox.io/v1alpha1
      resource: platforms
    - apiVersion: k8s.kubefox.io/v1alpha1
      resource: releases
  attachments:
    - apiVersion: v1
      resource: configmaps
      updateStrategy:
        method: InPlace
    - apiVersion: v1
      resource: namespaces
    - apiVersion: v1
      resource: secrets
      updateStrategy:
        method: InPlace
    - apiVersion: apps/v1
      resource: deployments
    - apiVersion: batch/v1
      resource: cronjobs
      updateStrategy:
        method: Recreate
    - apiVersion: k8s.kubefox.io/v1alpha1
      resource: componentsets
    - apiVersion: metacontroller.k8s.io/v1alpha1
      resource: compositecontrollers
      updateStrategy:
        method: Recreate
    - apiVersion: metacontroller.k8s.io/v1alpha1
      resource: decoratorcontrollers
      updateStrategy:
        method: Recreate
    - apiVersion: traefik.containo.us/v1alpha1
      resource: ingressroutes
      updateStrategy:
        method: Recreate
    - apiVersion: traefik.containo.us/v1alpha1
      resource: middlewares
      updateStrategy:
        method: Recreate
  hooks:
    sync:
      webhook:
        url: http://127.0.0.1:8080/sync?kf-release-environment=kubefox&kf-release-system=kubefox&kf-release-target=platform:operator&kf-release-event-type=io.kubefox.kubernetes_request
    customize:
      webhook:
        url: http://127.0.0.1:8080/customize?kf-release-environment=kubefox&kf-release-system=kubefox&kf-release-target=platform:operator&kf-release-event-type=io.kubefox.kubernetes_request
