apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubefox.vaultName" . }}
  labels:
    {{- include "kubefox.labels" . | nindent 4 }}
  {{- with  .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubefox.vaultName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubefox.vaultName" . }}
    namespace: {{ .Release.Namespace }}
