apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.vault.fullnameOverride }}
  labels:
    {{- include "kubefox.labels" . | nindent 4 }}
  {{- with  .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.vault.fullnameOverride }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.vault.fullnameOverride }}
    namespace: {{ .Release.Namespace }}
