apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vault.fullnameOverride }}-env
  labels:
    {{- include "kubefox.labels" . | nindent 4 }}
  {{- with  .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
data:
  KUBEFOX_INSTANCE: {{ include "kubefox.fullname" . | b64enc }}
  KUBEFOX_NAMESPACE: {{ .Release.Namespace | b64enc }}
