---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kfp-runtime-server
  labels:
    app.kubernetes.io/component: runtime-server
    {{- include "kubefox.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubefox.fullname" . }}-runtime-server
  labels:
    app.kubernetes.io/component: runtime-server
    {{- include "kubefox.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubefox.fullname" . }}-runtime-server
  labels:
    app.kubernetes.io/component: runtime-server
    {{- include "kubefox.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kfp-runtime-server
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubefox.fullname" . }}-runtime-server
