apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.runtime.server.service.name }}
  labels:
    app.kubernetes.io/component: runtime-server
    {{- include "kubefox.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.runtime.server.service.port }}
      targetPort: {{ .Values.runtime.server.service.port }}
  selector:
    app.kubernetes.io/component: runtime-server
    {{- include "kubefox.selectorLabels" . | nindent 4 }}
